### ISSUE TITLE
Missing secret fails silently

### ISSUE THREAD

**Issue by bergman** [spotify/styx#63]

**Comment by rouzwawi** [comment]
I'm guessing this refers to:

```
 Failed the docker starting procedure for bq-upload-user-sessions#BQLoad_DistCpFromOnPremise_UserSessionsAggregatedBySetType#2017-02-28
   java.lang.reflect.UndeclaredThrowableException: null
   at com.sun.proxy.$Proxy29.start(Unknown Source)
   at com.spotify.styx.state.handlers.DockerRunnerHandler.dockerRunnerStart(DockerRunnerHandler.java:136)
   at com.spotify.styx.state.handlers.DockerRunnerHandler.transitionInto(DockerRunnerHandler.java:68)
   at com.spotify.styx.state.FanOutputHandler.transitionInto(FanOutputHandler.java:44)
   at com.spotify.styx.state.FanOutputHandler.transitionInto(FanOutputHandler.java:44)
   at com.spotify.styx.state.QueuedStateManager.lambda$process$5(QueuedStateManager.java:279)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
   at java.lang.Thread.run(Thread.java:745)
   Caused by: java.lang.reflect.InvocationTargetException: null
   at sun.reflect.GeneratedMethodAccessor147.invoke(Unknown Source)
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   at java.lang.reflect.Method.invoke(Method.java:497)
   at com.spotify.styx.monitoring.MeteredProxy.invoke(MeteredProxy.java:64)
   at com.sun.proxy.$Proxy29.start(Unknown Source)
   at com.spotify.styx.state.handlers.DockerRunnerHandler.dockerRunnerStart(DockerRunnerHandler.java:136)
   at com.spotify.styx.state.handlers.DockerRunnerHandler.transitionInto(DockerRunnerHandler.java:68)
   at com.spotify.styx.state.FanOutputHandler.transitionInto(FanOutputHandler.java:44)
   at com.spotify.styx.state.FanOutputHandler.transitionInto(FanOutputHandler.java:44)
   at com.spotify.styx.state.QueuedStateManager.lambda$process$5(QueuedStateManager.java:279)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
   at java.lang.Thread.run(Thread.java:745)
   Caused by: com.spotify.styx.docker.InvalidExecutionException: Referenced secret 'bq-upload-user-sessions-secret' was not found
   at com.spotify.styx.docker.KubernetesDockerRunner.lambda$start$0(KubernetesDockerRunner.java:107)
   at java.util.Optional.ifPresent(Optional.java:159)
   at com.spotify.styx.docker.KubernetesDockerRunner.start(KubernetesDockerRunner.java:103)
   at com.spotify.styx.docker.RoutingDockerRunner.start(RoutingDockerRunner.java:51)
   at sun.reflect.GeneratedMethodAccessor147.invoke(Unknown Source)
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   at java.lang.reflect.Method.invoke(Method.java:497)
   at com.spotify.styx.monitoring.MeteredProxy.invoke(MeteredProxy.java:64)
   at com.sun.proxy.$Proxy29.start(Unknown Source)
   at com.spotify.styx.state.handlers.DockerRunnerHandler.dockerRunnerStart(DockerRunnerHandler.java:136)
   at com.spotify.styx.state.handlers.DockerRunnerHandler.transitionInto(DockerRunnerHandler.java:68)
   at com.spotify.styx.state.FanOutputHandler.transitionInto(FanOutputHandler.java:44)
   at com.spotify.styx.state.FanOutputHandler.transitionInto(FanOutputHandler.java:44)
   at com.spotify.styx.state.QueuedStateManager.lambda$process$5(QueuedStateManager.java:279)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
   at java.lang.Thread.run(Thread.java:745)
```

Which in turn causes

```
   java.lang.NullPointerException: Argument shouldn't be null: 'message' argument in static method invocation: 'runError' in class com.spotify.styx.model.Event
   at com.spotify.styx.model.Event.runError(Event.java:141)
   at com.spotify.styx.state.handlers.DockerRunnerHandler.transitionInto(DockerRunnerHandler.java:82)
   at com.spotify.styx.state.FanOutputHandler.transitionInto(FanOutputHandler.java:44)
   at com.spotify.styx.state.FanOutputHandler.transitionInto(FanOutputHandler.java:44)
   at com.spotify.styx.state.QueuedStateManager.lambda$process$5(QueuedStateManager.java:279)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
   at java.lang.Thread.run(Thread.java:745)
```

Seems the `InvalidExecutionException` that is thrown is now wrapped up in reflection exceptions because of `MeteredProxy`.

**Comment by rouzwawi** [comment]
This causes an infinite retry-loop of (SUBMITTED -> TIMEOUT -> QUEUED -> SUBMITTING) which does not increment the try-count.

Maybe we should also fix that. Timeouts should add to the try count.

**Comment by rouzwawi** [comment]
And it explains why we have a high numer of states in `SUBMITTING`:

<img width="760" alt="screen shot 2017-03-01 at 14 59 54" src="https://cloud.githubusercontent.com/assets/655452/23478607/d8934f28-fe8f-11e6-8531-3b040366fff0.png">
