### ISSUE TITLE
Not able to run tests locally

### ISSUE THREAD

**Issue by YawningMamba** [spotify/styx#956]
Hello,

Not sure if this counts as and issue but I'm trying to run `mvn clean verify` locally but continually fail to do it so help would be much appreciated.

The test I'm stuck on right now is this one `com.spotify.styx.client.GoogleIdTokenAuthTest`

```
[ERROR] testServiceAccountCredentialsWithAccessToken(com.spotify.styx.client.GoogleIdTokenAuthTest)  Time elapsed: 1.947 s  <<< ERROR!
com.google.cloud.storage.StorageException: styx-test-user@test-styxbdXXXXXXXX.iam.gserviceaccount.com does not have storage.objects.get access to the Google Cloud Storage object.
	at com.spotify.styx.client.GoogleIdTokenAuthTest.testServiceAccountCredentialsWithAccessToken(GoogleIdTokenAuthTest.java:180)

[ERROR] testServiceAccountCredentialsWithAccessTokenFailsIfMissingEmailScope(com.spotify.styx.client.GoogleIdTokenAuthTest)  Time elapsed: 0.047 s  <<< ERROR!
com.google.cloud.storage.StorageException: styx-test-user@test-styxbdXXXXXXXX.iam.gserviceaccount.com does not have storage.objects.get access to the Google Cloud Storage object.
	at com.spotify.styx.client.GoogleIdTokenAuthTest.testServiceAccountCredentialsWithAccessTokenFailsIfMissingEmailScope(G

[ERROR] testServiceAccountWithoutTokenCreatorRoleOnSelfFails(com.spotify.styx.client.GoogleIdTokenAuthTest)  Time elapsed: 594.514 s  <<< ERROR!
com.google.api.gax.rpc.UnavailableException: io.grpc.StatusRuntimeException: UNAVAILABLE: Credentials failed to obtain metadata
Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: Credentials failed to obtain metadata
Caused by: java.io.IOException: Error requesting access token
Caused by: com.google.api.client.http.HttpResponseException: 
403 Forbidden

[ERROR] testImpersonatedCredentials(com.spotify.styx.client.GoogleIdTokenAuthTest)  Time elapsed: 570.659 s  <<< ERROR!
com.google.api.gax.rpc.UnavailableException: io.grpc.StatusRuntimeException: UNAVAILABLE: Credentials failed to obtain metadata
Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: Credentials failed to obtain metadata
Caused by: java.io.IOException: Error requesting access token

[ERROR] testServiceAccountCredentials(com.spotify.styx.client.GoogleIdTokenAuthTest)  Time elapsed: 0.069 s  <<< ERROR!
com.google.cloud.storage.StorageException: styx-test-user@test-styxbdXXXXXXXX.iam.gserviceaccount.com does not have storage.objects.get access to the Google Cloud Storage object.
	at com.spotify.styx.client.GoogleIdTokenAuthTest.testServiceAccountCredentials(GoogleIdTokenAuthTest.java:146)

```

I managed to get passed the `com.spotify.styx.api.ServiceAccountsTest` by creating the following Terraform script

```
locals {
  styx_project = "test-styx"
  styx_test_user = "styx-test-user"
  service_account_access = "storage.objectViewer"
  service_apis = ["iamcredentials.googleapis.com", "storage.googleapis.com", "storage-api.googleapis.com"]
}

provider "google" {
}

resource "random_id" "styx_id" {
  byte_length = 4
  prefix = local.styx_project
}

resource "google_project" "test_styx" {
  name = local.styx_project
  project_id = random_id.styx_id.hex
}

resource "google_service_account" "styx_test_user" {
  account_id   = local.styx_test_user
  project = google_project.test_styx.project_id
  display_name = "Styx Test Service Account"
}

resource "google_service_account_key" "styx_test_user_key" {
  service_account_id = google_service_account.styx_test_user.name
}

resource "google_project_iam_binding" "styx_project_iam_binding" {
  project = google_project.test_styx.project_id
  role = format("%s/%s", "roles", local.service_account_access)
  members = ["serviceAccount:${google_service_account.styx_test_user.email}"]
}

resource "google_project_service" "services" {
  for_each = toset( local.service_apis )
  project = google_project.test_styx.project_id
  service = each.key
}

output "project_id" {
  value = google_project.test_styx.project_id
}

output "styx_test_user" {
  value = google_service_account.styx_test_user.email
}

output "styx_test_user_key" {
  value = base64decode(google_service_account_key.styx_test_user_key.private_key)
  sensitive = true
}
```

Then changing `ServiceAccountsTest#SERVICE_ACCOUNT` to the following

```
  private static final String SERVICE_ACCOUNT = System.getProperty(
          "styxTestServiceAccount",
          "styx-test-user@styx-oss-test.iam.gserviceaccount.com");
```

export the credentials, project number to env and then run maven with the following line

```
mvn clean verify -DargLine="-DstyxTestServiceAccount=styx-test-user@test-styxbdXXXXXXXX.iam.gserviceaccount.com"
```

The reason I added the `storage.objectViewer` to the account is because of the error I get from `GoogleIdTokenAuthTest` however I just noticed that I probably get this error because I don't have access to the `gs://styx-oss-test/styx-test-user.json` which I guess contains the styx-test-user credentials, what does it contain?

Right now my plan is to create `styx-test-unusable-user`, remap the user in the test, make `gs://styx-oss-test/styx-test-user.json` Uri to constant that can be remapped to read a local file and I have no clue what to do with `styx.foo.bar` host so I have just mapped the domain it to my localhost expecting it to have something to do with the `metadataServer` but I have no clue if this is a good approach please advice.

Is there something more that I will encounter after the client tests that I need to consider?

It would be great if I can get some help setting this up, if there is no time you can close this or I'll it if I give up or succeed.

**Comment by tnsetting** [comment]
Hi 

The tests in `GoogleIdTokenAuthTest` is mostly about creating ID token for styx client. `gs://styx-oss-test/styx-test-user.json` contains a key file for a google service account. I think you can replace it with your own key file. I am sorry that these path and service account are hardcoded.

**Comment by YawningMamba** [comment]
Thanks for the information. I'm still not able to get it running to completion even after these changes but I'm closer now.
